##
##  Makefile -- Build procedure for sample dosdetector Apache module
##  Autogenerated via ``apxs -n dosdetector -g''.
##

#   the used tools
APXS=/usr/sbin/apxs
APACHECTL=apachectl

#   additional user defines, includes and libraries
#DEF=-Dmy_define=my_value
#INC=-Imy/include/dir
#LIB=-Lmy/lib/dir -lmylib

#   the default target
all: mod_dosdetector.so

#   compile the DSO file
mod_dosdetector.so: mod_dosdetector.c
	$(APXS) -c $(DEF) $(INC) $(LIB) mod_dosdetector.c

#   install the DSO file into the Apache installation
#   and activate it in the Apache configuration
install: all
	$(APXS) -c -i -a -n 'dosdetector' mod_dosdetector.c

#   cleanup
clean:
	-rm -f mod_dosdetector.o mod_dosdetector.so mod_dosdetector.lo mod_dosdetector.slo mod_dosdetector.la

#   simple test
test: reload
	lynx -mime_header http://localhost/dosdetector

#   reload the module by installing and restarting Apache
reload: install restart

#   the general Apache start/restart/stop procedures
start:
	$(APACHECTL) start
restart:
	$(APACHECTL) restart
stop:
	$(APACHECTL) stop

